from datetime import date
from typing import Protocol
from uuid import UUID

from src.domain.daily_planning import Action, Day
from src.domain.inbox import InboxItem


class DayRepository(Protocol):
    def get_by_date(self, day_date: date) -> Day | None: ...

    def save(self, day: Day) -> None: ...

    def get_action(self, action_id: UUID) -> Action | None: ...

    def update_action(self, action: Action) -> None: ...

    def delete_action(self, action_id: UUID) -> bool: ...

    def move_action(self, action_id: UUID, target_date: date) -> Action | None: ...


class InboxRepository(Protocol):
    def get_all(self) -> list[InboxItem]: ...

    def add(self, item: InboxItem) -> None: ...

    def get(self, item_id: UUID) -> InboxItem | None: ...

    def update(self, item: InboxItem) -> None: ...

    def delete(self, item_id: UUID) -> bool: ...

    def schedule(self, item_id: UUID, day_date: date) -> Action | None: ...
